### ISSUE TITLE
Prevent certain items from being swappable

### ISSUE THREAD

**Issue by Odaym** [askerov/DynamicGrid#18]
Is it possible for me to prevent certain items inside the adapter to not swap with others when they are hovered over? to just stay in their place when startEditMode is on?

The identifier I have for these items that I dont want to move is `id` and its always static, I want that all the time, the items that have these two id's should never swap with any other item

**Comment by marleyiam** [comment]
+1 for this, I'm also trying to find a solution =/ 
If I get some green lights I'll be back.

**Comment by Odaym** [comment]
late response to this but back then when I had the problem it was with the last element of the listview to prevent it from being swappable, what I ended up doing was adding that last item as the listview's footer, the same would apply to the header. Very hard to imagine a reasonable scenario that involves items in the middle to not be swappable..
