### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by manhhoangxuan** [askerov/DynamicGrid#3]
I have encounter an more exception here
I run on android 2.3.3 emulator
10-23 10:14:18.403: E/AndroidRuntime(2478): FATAL EXCEPTION: main
10-23 10:14:18.403: E/AndroidRuntime(2478): java.lang.NullPointerException
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.widget.AdapterView.getPositionForView(AdapterView.java:581)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at org.askerov.dynamicgid.DynamicGridView.handleCellSwitch(DynamicGridView.java:704)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at org.askerov.dynamicgid.DynamicGridView.onTouchEvent(DynamicGridView.java:457)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.View.dispatchTouchEvent(View.java:3885)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:903)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:942)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1691)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1125)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1675)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2194)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1878)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.os.Looper.loop(Looper.java:123)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at android.app.ActivityThread.main(ActivityThread.java:3683)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at java.lang.reflect.Method.invokeNative(Native Method)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at java.lang.reflect.Method.invoke(Method.java:507)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
10-23 10:14:18.403: E/AndroidRuntime(2478):     at dalvik.system.NativeStart.main(Native Method)

**Comment by akingyin1987** [comment]
我也遇到了这个问题
