### ISSUE TITLE
Scrolling in edit mode

### ISSUE THREAD

**Issue by Odaym** [askerov/DynamicGrid#34]
Well, your library is now being used in production in a live app! Thanks a lot for the help you've provided so far. I wanted to ask about scrolling when in Edit mode. Right now when you place your finger to scroll, the touch is being stolen by the items on the screen and they instantly start moving.

If I could set the listener on the items for onItemLongClickListener, then it would have to take a long click to make them move, therefore allowing for natural scroll. I was not able to figure it out so far, help would be appreciated again, thanks a lot

**Comment by chengwentao** [comment]
hello Odaym,
if my GridView has a ScrollView as his parent view, when I touch the item to move, the ScrollView does not move by, how to solve this problem?

**Comment by iamutkarshtiwari** [comment]
Check the function at line `490` in this file: https://gist.github.com/iamutkarshtiwari/4b130d0d26a77896b8dfc8cadcee3fc2
