### ISSUE TITLE
Drag And Drop in ViewPager

### ISSUE THREAD

**Issue by Raheel-Adnan** [askerov/DynamicGrid#4]
Hi,
I love DynamicGridView, It works like charm. But there is one issue, It doesn't work if we implement it in ViewPager. Is there a way I could use this code in ViewPager? Waiting for your fruitful response.
Thank you

**Comment by mani051990** [comment]
HI, 
How can i drag and drop items between pages using dynamicGridView. please help me in this.

**Comment by yuxingfafu** [comment]
@mani051990 could you finish the effect? drag between pages? thank you
