### ISSUE TITLE
Can't run sample project

### ISSUE THREAD

**Issue by GrahamBriggs** [askerov/DynamicGrid#44]
Sorry to post such a simple problem, but I am unable to run the sample project.  I was able to build after adding the dynamicgrid project in the build path of the example project. However, when I run the example project on the device, it crashes with this error:

10-22 23:05:07.275: E/dalvikvm(7303): Could not find class 'org.askerov.dynamicgrid.DynamicGridView', referenced from method org.askerov.dynamicgrid.example.GridActivity.onCreate

I searched for an answer, and found some comments regarding use of "/lib" versus "/libs".  However, I am a total novice at Java and I really don't understand how to properly include one project in another project. 

I thank you in advance for your time to consider this problem

**Comment by RegisAG** [comment]
Same problem here. I imported both projects in Eclipse (GridActivity and dynamicgrid), mentioned dynamicgrid in the build path of GridActivity. No error at compile. But crash on setContentView(R.layout.activity_grid); (of the onCreate method) at launchtime.

Can you detail how you fix the problem ? Thanks !
