### ISSUE TITLE
Lost the last element

### ISSUE THREAD

**Issue by marinat** [askerov/DynamicGrid#60]
If in example apk I drag element to last position sometimes it disappears.

**Comment by marinat** [comment]
reproduced on android 5 lg g3

**Comment by marinat** [comment]
It happens in method reset() of DynamicGridView. I changed to
//ugly fix for unclear disappearing items after reorder

        for(int i=0; i<getChildCount(); ++i) {
            View nextChild =getChildAt(i);
            if (nextChild != null) {
            	nextChild.setVisibility(View.VISIBLE);
            }
        }
because I have up to 20 elements, but it not good fix

**Comment by denisk20** [comment]
Does the item stays invisible after you release or does it appear at the end? I sometimes face the situation when it disappears but then appears, which I can leave with so far.
Also, which element are you dragging to the last position? Is it very last element relative to initial screen or relative the whole list of cheeses?

**Comment by marinat** [comment]
Item stays invisible after I release. It can appear again if I slowly drag new item at the end of grid.

I use items at end of grid. let's say, the last 12 items before last.
