### ISSUE TITLE
 Weird bug

### ISSUE THREAD

**Issue by slmyldz** [askerov/DynamicGrid#72]
![unnamed](https://cloud.githubusercontent.com/assets/5596316/9992156/b9ebde70-6078-11e5-8b14-d01be59356f0.png)

Sometimes layout shown like that. I didn't understand why ? On the top image of layout (weird exit image) act like the top view hierarchy. But  on my  phone (Nexus 5 - 6.0) working perfect. 
Like that:
![screenshot_20150921-155657](https://cloud.githubusercontent.com/assets/5596316/9992294/c5765a8a-6079-11e5-884c-6160c5f4f437.png)

**Comment by slm** [comment]
this bug because of about opengl version
